/**
 * "First open" end-to-end performance benchmark: measures the FULL pipeline a user actually waits
 * on when opening Git Graph on a large repository for the first time - real `git` processes spawned
 * against a large REAL repository on disk (not fabricated in-memory data, unlike webviewUiPerf.test.ts),
 * through to the compiled webview bundle (media/out.min.js) rendering the result in jsdom.
 *
 * It also runs the SAME backend request twice (COLD: a fresh DataSource, as on the very first open
 * after VS Code starts; WARM: a second fresh DataSource against the same on-disk repo moments later,
 * as when re-opening the view again in the same session) and compares them. This directly tests
 * whether "slow on first open, fast afterwards" is something the extension's code controls, or an
 * external cold-cache effect (the OS hasn't yet paged a large .git directory into memory) that no
 * amount of code change fixes - the first read of a multi-GB repository from disk is inherently
 * slower than reading the same bytes again a moment later once the OS has cached them.
 *
 * All repository data (author names/emails, branch/tag names, commit messages) is entirely
 * FICTIONAL and generated by a seeded PRNG - nothing is derived from any real repository. Scale is
 * shaped after a large, actively-developed project (thousands of commits, 100+ branches).
 */
import * as vscode from './mocks/vscode';
jest.mock('vscode', () => vscode, { virtual: true });
jest.mock('../src/askpass/askpassManager');
jest.mock('../src/logger');

/**
 * @jest-environment jsdom
 */
import * as cp from 'child_process';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { ConfigurationChangeEvent } from 'vscode';
import { DataSource } from '../src/dataSource';
import { CommitOrdering, GitCommit, GitStash } from '../src/types';
import { Logger } from '../src/logger';
import * as utils from '../src/utils';
import { EventEmitter } from '../src/utils/event';

declare const document: any;
declare const window: any;
declare const Event: any;
declare const MessageEvent: any;

/* Any single test (or beforeAll/afterAll hook) that exceeds 3 minutes is a failure. */
jest.setTimeout(180000);

const BASE_EPOCH = 1784599200; // 2026-07-21T10:00:00+00:00
const hour = 3600;

/* Repository scale: the same order of magnitude as a large real-world monorepo */
const TRUNK_COMMITS = 1800;
const BRANCHES = 110;
const TAGS = 200;
const INITIAL_LOAD_COMMITS = 300; // what the webview requests on first paint (initialLoadCommits)

/* ==================== Fictional data (identical pools to webviewUiPerf.test.ts) ==================== */

const FIRST_NAMES = ['Ava', 'Liam', 'Noah', 'Mia', 'Ethan', 'Zoe', 'Kai', 'Priya', 'Diego', 'Freya', 'Omar', 'Nina', 'Leo', 'Grace', 'Marcus'];
const LAST_NAMES = ['Stone', 'Cross', 'Vance', 'Blackwood', 'Rivers', 'Bennett', 'Sutton', 'Nandan', 'Salas', 'Lindqvist'];
const MODULE_POOL = ['orbit', 'ledger', 'beacon', 'lattice', 'harbor', 'pixel', 'nimbus', 'cobalt', 'ripple', 'forge', 'atlas', 'quartz', 'vector', 'meadow', 'signal'];
const MESSAGE_TEMPLATES = [
	'feat: add %s pagination support', 'fix: correct %s timeout handling', 'refactor: simplify %s pipeline internals',
	'chore: bump %s dependency versions', 'docs: expand %s usage guide', 'test: add regression coverage for %s'
];

function mulberry32(seed: number): () => number {
	let s = seed;
	return () => {
		s |= 0; s = (s + 0x6D2B79F5) | 0;
		let t = Math.imul(s ^ (s >>> 15), 1 | s);
		t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
		return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
	};
}
function pick<T>(rng: () => number, arr: ReadonlyArray<T>): T {
	return arr[Math.floor(rng() * arr.length)];
}
function authorPool(count: number): { name: string, email: string }[] {
	const authors = [];
	for (let i = 0; i < count; i++) {
		const first = FIRST_NAMES[i % FIRST_NAMES.length];
		const last = LAST_NAMES[Math.floor(i / FIRST_NAMES.length) % LAST_NAMES.length];
		authors.push({ name: first + ' ' + last, email: (first + '.' + last).toLowerCase() + '@example.com' });
	}
	return authors;
}
const AUTHORS = authorPool(45);

/** Run a Git command synchronously (used to BUILD the test repository). */
function git(cwd: string, args: string[]) {
	const result = cp.spawnSync('git', args, { cwd: cwd, encoding: 'utf8' });
	if (result.status !== 0) {
		throw new Error('git ' + args.join(' ') + ' failed in ' + cwd + ':\n' + result.stderr);
	}
	return (result.stdout || '').trim();
}

/** Builder of a `git fast-import` stream (trimmed to what a plain, non-Gerrit history needs). */
class FastImport {
	private chunks: string[] = [];
	private mark = 0;

	constructor(private readonly repo: string) { }

	private data(content: string) {
		this.chunks.push('data ' + Buffer.byteLength(content, 'utf8'));
		this.chunks.push(content);
	}

	public commit(ref: string, epoch: number, fromMark?: number) {
		this.mark++;
		const rng = mulberry32(this.mark);
		const author = pick(rng, AUTHORS);
		const message = pick(rng, MESSAGE_TEMPLATES).replace('%s', pick(rng, MODULE_POOL)) + '\n';
		this.chunks.push('commit ' + ref, 'mark :' + this.mark);
		const identity = author.name + ' <' + author.email + '> ' + epoch + ' +0000';
		this.chunks.push('author ' + identity, 'committer ' + identity);
		this.data(message);
		if (fromMark !== undefined) this.chunks.push('from :' + fromMark);
		return this.mark;
	}

	/** Create a merge commit on `ref`, with `fromMark` as the first parent and `mergeMark` as the second. */
	public merge(ref: string, epoch: number, fromMark: number, mergeMark: number) {
		this.mark++;
		const rng = mulberry32(this.mark);
		const author = pick(rng, AUTHORS);
		this.chunks.push('commit ' + ref, 'mark :' + this.mark);
		const identity = author.name + ' <' + author.email + '> ' + epoch + ' +0000';
		this.chunks.push('author ' + identity, 'committer ' + identity);
		this.data('merge: bring in a feature branch\n');
		this.chunks.push('from :' + fromMark, 'merge :' + mergeMark);
		return this.mark;
	}

	public tag(name: string, mark: number, epoch: number) {
		this.chunks.push('tag ' + name, 'from :' + mark, 'tagger Dev <dev@example.com> ' + epoch + ' +0000');
		this.data('release ' + name + '\n');
	}

	public run() {
		const result = cp.spawnSync('git', ['fast-import', '--quiet'], { cwd: this.repo, input: this.chunks.join('\n') + '\ndone\n', encoding: 'utf8' });
		if (result.status !== 0) {
			throw new Error('git fast-import failed in ' + this.repo + ':\n' + result.stderr);
		}
	}
}

/**
 * Build a large fictional repository ON DISK (a trunk with many feature branches, most merged
 * back, some left open, and many tags scattered across the trunk) - the same DAG shape as
 * webviewUiPerf.test.ts's in-memory generator, but this time emitting real Git objects via
 * `git fast-import`, so the DataSource operations below spawn real `git` processes.
 */
function buildRepository(repo: string) {
	const rng = mulberry32(0xC0FFEE);
	const epoch = (i: number) => BASE_EPOCH + i * hour;
	const imp = new FastImport(repo);

	let trunkTip = imp.commit('refs/heads/main', epoch(1));
	const trunkMarks = [trunkTip];
	for (let i = 1; i < TRUNK_COMMITS; i++) {
		trunkTip = imp.commit('refs/heads/main', epoch(i + 1), trunkTip);
		trunkMarks.push(trunkTip);
	}

	const perBranch = Math.max(1, Math.round((TRUNK_COMMITS * 0.6) / BRANCHES));
	const branchSpan = perBranch * 2 + 5; // epoch slots reserved per branch, wide enough that its commits never overlap the next branch's
	for (let b = 0; b < BRANCHES; b++) {
		const branchName = 'feature/' + pick(rng, MODULE_POOL) + '-' + (b + 1);
		let tip = trunkMarks[Math.floor(rng() * trunkMarks.length)];
		const branchCommitCount = 1 + Math.floor(rng() * perBranch * 2);
		const branchEpoch = TRUNK_COMMITS + 100 + b * branchSpan;
		for (let c = 0; c < branchCommitCount; c++) tip = imp.commit('refs/heads/' + branchName, epoch(branchEpoch + c), tip);

		if (rng() < 0.65) {
			// merged back into the trunk (a real 2-parent merge commit)
			trunkTip = imp.merge('refs/heads/main', epoch(branchEpoch + branchCommitCount + 1), trunkTip, tip);
			trunkMarks.push(trunkTip);
		}
		// else: left as an open branch ref (already created above by the `commit` calls)
	}

	for (let t = 0; t < TAGS; t++) {
		const mark = trunkMarks[Math.floor(rng() * trunkMarks.length)];
		imp.tag('v' + (1 + Math.floor(t / 20)) + '.' + (t % 20) + '.0', mark, epoch(TRUNK_COMMITS + 200 + t));
	}

	imp.run();
	git(repo, ['checkout', '-q', 'main']);
}

/* Measure the wall-clock time (ms) of an async operation. */
async function timed<T>(fn: () => Promise<T>): Promise<{ value: T, ms: number }> {
	const start = Date.now();
	const value = await fn();
	return { value: value, ms: Date.now() - start };
}

/* Count how many Git processes an async operation spawns. */
async function countSpawns<T>(fn: () => Promise<T>): Promise<{ value: T, ms: number, spawns: number }> {
	const realSpawn = cp.spawn.bind(cp);
	let spawns = 0;
	const spy = jest.spyOn(cp, 'spawn').mockImplementation(((command: string, args: readonly string[], options: any) => {
		spawns++;
		return realSpawn(command, args as any[], options);
	}) as any);
	try {
		const { value, ms } = await timed(fn);
		return { value: value, ms: ms, spawns: spawns };
	} finally {
		spy.mockRestore();
	}
}

function rmRecursive(target: string) {
	if (!fs.existsSync(target)) return;
	for (const entry of fs.readdirSync(target)) {
		const entryPath = path.join(target, entry);
		try {
			if (fs.statSync(entryPath).isDirectory()) rmRecursive(entryPath);
			else fs.unlinkSync(entryPath);
		} catch (e) {
			// A Git subprocess may delete an entry (e.g. .git/index.lock) concurrently with
			// this cleanup: an entry that is already gone needs no removal.
			if (e.code !== 'ENOENT') throw e;
		}
	}
	fs.rmdirSync(target);
}

/* ==================== Webview bootstrap (drives media/out.min.js in jsdom) ==================== */

function makeConfig(): any {
	return {
		commitOrdering: 'date',
		commitDetailsView: { autoCenter: true, fileTreeCompactFolders: true, fileViewType: 'File Tree', location: 'Inline' },
		contextMenuActionsVisibility: {}, customBranchGlobPatterns: [], customEmojiShortcodeMappings: [], customPullRequestProviders: [],
		dateFormat: { type: 'relative', short: true, iso: false, string: '' },
		defaultColumnVisibility: { date: true, author: true, commit: true, signature: false },
		dialogDefaults: {}, enhancedAccessibility: false,
		fetchAndPrune: false, fetchAndPruneTags: false, fetchAvatars: false,
		gerrit: {
			enabled: false, remote: 'origin', fetchMode: 'latest', fetchLimit: 10, patchsets: 'latest', autoFetch: false,
			showChangeRefs: true, includeChangeCommits: true, showReviewProgress: true,
			showMetaCommits: 'collapsed', statusFilter: { new: true, merged: false, abandoned: false, wip: false },
			showPushButton: true, showControlsBar: true
		},
		graph: { colours: ['#0085d9'], style: 'rounded', issueLinking: {}, grid: { x: 10, y: 24, offsetX: 8, offsetY: 8, expandY: 8 } },
		initialLoadCommits: INITIAL_LOAD_COMMITS, keybindings: {}, loadMoreCommits: 300, loadMoreCommitsAutomatically: false,
		markdown: false, mute: { commitsNotAncestorsOfHead: false, mergeCommits: false }, onRepoLoad: { showCheckedOutBranch: null, showSpecificBranches: [] },
		referenceLabels: { branchLabelsAlignedToGraph: false, combineLocalAndRemoteBranchLabels: true, tagLabelsOnRight: false },
		showCommitBodyInline: false, stickyHeader: true, tabIconColourTheme: 'colour'
	};
}

function makeState(repo: string): any {
	return {
		avatar: null, config: makeConfig(), lastActiveRepo: repo, loadViewTo: null,
		repos: {
			[repo]: {
				cdvDivider: 50, cdvHeight: 50, columnWidths: null, commitOrdering: 'default', fileViewType: null, hideRemotes: [],
				includeCommitsMentionedByReflogs: null, issueLinkingConfig: {}, lastImportAt: 0, name: 'repo',
				onlyFollowFirstParent: null, onRepoLoadShowCheckedOutBranch: null, onRepoLoadShowSpecificBranches: null,
				pullRequestConfig: null, showRemoteBranches: false, showRemoteBranchesV2: null, showStashes: null,
				showTags: null, workspaceFolderIndex: null
			}
		},
		loadRepoInfoRefreshId: 1, loadCommitsRefreshId: 1
	};
}

const VIEW_HTML = '<div id="view" tabindex="-1">' +
	'<div id="controls"><span id="repoControl"><div id="repoDropdown" class="dropdown"></div></span>' +
	'<span id="branchControl"><div id="branchDropdown" class="dropdown"></div></span>' +
	'<span id="authorControl"><div id="authorDropdown" class="dropdown"></div></span>' +
	'<label id="showRemoteBranchesControl"><input type="checkbox" id="showRemoteBranchesCheckbox"></label>' +
	'<div id="currentBtn"></div><div id="findBtn"></div><div id="filterBtn"></div><div id="terminalBtn"></div><div id="settingsBtn"></div><div id="fetchBtn"></div><div id="refreshBtn"></div></div>' +
	'<div id="gerritControls"><span class="gerritRowLabel">Gerrit:</span>' +
	'<span id="gerritFilterControl"></span><div id="gerritAmendBtn"></div><div id="gerritSubmitBtn"></div><div id="gerritClearRefsBtn"></div></div>' +
	'<div id="content"><div id="commitGraph"></div><div id="commitTable"></div></div>' +
	'<div id="footer"></div></div>';

const BUNDLE = fs.readFileSync(path.join(__dirname, '..', 'media', 'out.min.js'), 'utf8');

interface Harness { sentMessages: any[]; }

function loadWebview(repo: string): Harness {
	document.body.innerHTML = VIEW_HTML;
	(window as any).Element.prototype.scroll = () => undefined;
	window.requestAnimationFrame = (cb: any) => { cb(); return 0; };
	window.cancelAnimationFrame = () => undefined;
	const harness: Harness = { sentMessages: [] };
	let webviewState: any;
	(globalThis as any).acquireVsCodeApi = () => ({
		postMessage: (msg: any) => { harness.sentMessages.push(msg); return undefined; },
		getState: () => webviewState,
		setState: (state: any) => { webviewState = state; }
	});
	// eslint-disable-next-line no-eval
	eval('var initialState = ' + JSON.stringify(makeState(repo)) + ', globalState = ' + JSON.stringify({ avatars: {} }) + ', workspaceState = ' + JSON.stringify({}) + ';\n' + BUNDLE);
	window.dispatchEvent(new Event('load'));
	return harness;
}

function respondToRepoInfo(harness: Harness, branchNames: string[], head: string | null, remotes: string[]) {
	const msg = harness.sentMessages.filter((m) => m.command === 'loadRepoInfo').pop();
	expect(msg).toBeDefined();
	window.dispatchEvent(new MessageEvent('message', { data: {
		command: 'loadRepoInfo', refreshId: msg.refreshId, error: null,
		branches: branchNames, head: head, remotes: remotes, stashes: [], isRepo: true
	} }));
}

function respondToLoadCommits(harness: Harness, commits: any[], moreAvailable: boolean, head: string | null) {
	const msg = harness.sentMessages.filter((m) => m.command === 'loadCommits').pop();
	expect(msg).toBeDefined();
	window.dispatchEvent(new MessageEvent('message', { data: {
		command: 'loadCommits', refreshId: msg.refreshId, error: null, head: head, tags: [],
		moreCommitsAvailable: moreAvailable, onlyFollowFirstParent: false, gerritStates: null, commits: commits
	} }));
}

/* ==================== The benchmark ==================== */

interface ReportRow { phase: string, ms: number, spawns: number | null }
const report: ReportRow[] = [];
const record = (phase: string, ms: number, spawns: number | null = null) => { report.push({ phase: phase, ms: ms, spawns: spawns }); };

interface OpenResult {
	repoInfo: { branches: string[], head: string | null, remotes: string[], stashes: GitStash[] };
	commitData: { commits: GitCommit[], head: string | null, moreCommitsAvailable: boolean };
	backendMs: number;
}

describe('First-open performance (real Git, real repository on disk, fictional data)', () => {
	let onDidChangeConfiguration: EventEmitter<ConfigurationChangeEvent>;
	let onDidChangeGitExecutable: EventEmitter<utils.GitExecutable>;
	let logger: Logger;
	let repo: string, root: string;

	beforeAll(() => {
		onDidChangeConfiguration = new EventEmitter<ConfigurationChangeEvent>();
		onDidChangeGitExecutable = new EventEmitter<utils.GitExecutable>();
		logger = new Logger();

		root = fs.mkdtempSync(path.join(os.tmpdir(), 'gg-first-open-'));
		repo = path.join(root, 'repo');
		fs.mkdirSync(repo);
		git(repo, ['init', '-q', '-b', 'main']);

		const buildStart = Date.now();
		buildRepository(repo);
		record('0. repository build on disk (~' + (TRUNK_COMMITS + BRANCHES * 3) + ' commits, ' + BRANCHES + ' branches, ' + TAGS + ' tags)', Date.now() - buildStart, null);
	});

	afterAll(() => {
		if (root !== undefined) rmRecursive(root);
		logger.dispose();
		onDidChangeGitExecutable.dispose();
		onDidChangeConfiguration.dispose();

		/* eslint-disable no-console */
		const pad = (s: string, n: number) => s + ' '.repeat(Math.max(0, n - s.length));
		console.log('\n==================== GIT GRAPH FIRST-OPEN BENCHMARK (real Git, fictional repository) ====================');
		for (const entry of report) {
			console.log('  ' + pad(entry.phase, 70) + pad(entry.ms.toFixed(0).padStart(7) + ' ms', 12) + (entry.spawns !== null ? entry.spawns + ' git spawns' : ''));
		}
		console.log('=============================================================================================================\n');
		/* eslint-enable no-console */
	});

	/**
	 * Runs a single "open Git Graph" backend request against a BRAND NEW DataSource instance (no
	 * warm state of any kind carried over) - what the extension actually does every time the view
	 * is opened, whether that's the first time this VS Code session or the tenth.
	 */
	async function openOnce(label: string): Promise<OpenResult> {
		const source = new DataSource({ path: 'git', version: '2.30.0' }, onDidChangeConfiguration.subscribe, onDidChangeGitExecutable.subscribe, logger);
		try {
			const repoInfo = await countSpawns(() => source.getRepoInfo(repo, true, false, []));
			record(label + ': repo info (branches/remotes/tags/stashes)', repoInfo.ms, repoInfo.spawns);
			expect(repoInfo.value.error).toBeNull();
			expect(repoInfo.value.branches.length).toBeGreaterThan(BRANCHES);

			const commitData = await countSpawns(() => source.getCommits(
				repo, null, null, INITIAL_LOAD_COMMITS, true, true, false, false,
				CommitOrdering.Date, repoInfo.value.remotes, [], repoInfo.value.stashes, null, false
			));
			record(label + ': commit log (first ' + INITIAL_LOAD_COMMITS + ' commits)', commitData.ms, commitData.spawns);
			expect(commitData.value.error).toBeNull();
			expect(commitData.value.commits.length).toBe(INITIAL_LOAD_COMMITS);

			return { repoInfo: repoInfo.value, commitData: commitData.value, backendMs: repoInfo.ms + commitData.ms };
		} finally {
			source.dispose();
		}
	}

	let firstOpen: OpenResult;

	/* 1. COLD: the very first request against this repository (as on the first Git Graph open) */
	it('opens the repository for the first time (cold)', async () => {
		firstOpen = await openOnce('1. COLD (first open)');
	});

	/* 2. WARM: an identical request moments later (as when re-opening the view in the same session) */
	it('re-opens the same repository moments later (warm)', async () => {
		const warmOpen = await openOnce('2. WARM (re-open, same session)');

		const speedup = firstOpen.backendMs / Math.max(1, warmOpen.backendMs);
		record('=> cold vs warm backend speed-up', 0);
		// eslint-disable-next-line no-console
		console.log('\n  [cold backend: ' + firstOpen.backendMs + ' ms, warm backend: ' + warmOpen.backendMs + ' ms, ' + speedup.toFixed(1) + 'x]');
	});

	/* 3. The webview render of the COLD open's real data - the rest of what the user is waiting on */
	it('renders the webview for the first open (real branches + real commits)', async () => {
		const harness = loadWebview(repo);

		const repoInfoRender = await timed(async () => respondToRepoInfo(harness, firstOpen.repoInfo.branches, firstOpen.repoInfo.head, firstOpen.repoInfo.remotes));
		record('3. repo info -> branch/author dropdown build', repoInfoRender.ms);

		const commitsRender = await timed(async () => respondToLoadCommits(harness, firstOpen.commitData.commits, firstOpen.commitData.moreCommitsAvailable, firstOpen.commitData.head));
		record('4. commit table + graph render (' + firstOpen.commitData.commits.length + ' commits)', commitsRender.ms);
		expect(document.querySelectorAll('tr.commit').length).toBe(firstOpen.commitData.commits.length);

		const totalFirstOpen = firstOpen.backendMs + repoInfoRender.ms + commitsRender.ms;
		record('=> TOTAL first open (real Git backend + real webview render)', totalFirstOpen);
	});

	/**
	 * The actual reported bottleneck: a large number of UNTRACKED files (a big dependency tree that
	 * hasn't been committed, e.g. `node_modules`) makes `git status --untracked-files=all` slow.
	 * getCommits() used to await this status inline before the branch graph could be returned at
	 * all. Compares that BLOCKING behaviour against the fix (`deferUncommittedChanges: true`),
	 * which returns the graph as soon as log+refs are ready and fetches the status afterwards.
	 *
	 * The tree is deliberately NESTED (many small package-like directories, as a real
	 * `node_modules` looks), not flat: on Windows, `git status`'s cost is driven far more by the
	 * NUMBER OF DIRECTORIES it has to traverse (a syscall per directory) than by raw file count -
	 * a flat layout with the same file count understates the real-world slowdown by ~4-8x.
	 */
	describe('uncommitted changes on a large untracked working tree (BLOCKING vs DEFERRED first paint)', () => {
		const UNTRACKED_PACKAGE_DIRS = 15000;
		const UNTRACKED_FILES_PER_PACKAGE = 8; // ~120,000 untracked files across 15,000 nested "package" directories
		let blockingMs = 0;

		beforeAll(() => {
			const start = Date.now();
			const nodeModules = path.join(repo, 'node_modules');
			fs.mkdirSync(nodeModules);
			for (let p = 0; p < UNTRACKED_PACKAGE_DIRS; p++) {
				const pkgDir = path.join(nodeModules, 'pkg-' + p);
				const dir = path.join(pkgDir, 'lib');
				fs.mkdirSync(pkgDir);
				fs.mkdirSync(dir);
				for (let f = 0; f < UNTRACKED_FILES_PER_PACKAGE; f++) {
					fs.writeFileSync(path.join(dir, 'file-' + f + '.js'), '/* generated */\n');
				}
			}
			record('5. seed ' + (UNTRACKED_PACKAGE_DIRS * UNTRACKED_FILES_PER_PACKAGE) + ' untracked files across ' + UNTRACKED_PACKAGE_DIRS + ' nested dirs (simulated node_modules)', Date.now() - start, null);
		});

		afterAll(() => {
			rmRecursive(path.join(repo, 'node_modules'));
		});

		it('BLOCKING (pre-fix default): getCommits() waits for `git status` before the graph can render', async () => {
			const source = new DataSource({ path: 'git', version: '2.30.0' }, onDidChangeConfiguration.subscribe, onDidChangeGitExecutable.subscribe, logger);
			try {
				const repoInfo = await source.getRepoInfo(repo, true, false, []);
				const blocking = await timed(() => source.getCommits(
					repo, null, null, INITIAL_LOAD_COMMITS, true, true, false, false,
					CommitOrdering.Date, repoInfo.remotes, [], repoInfo.stashes, null, false, null, false
				));
				blockingMs = blocking.ms;
				record('6. BLOCKING first paint (git status gates the response)', blocking.ms);
				expect(blocking.value.error).toBeNull();
			} finally {
				source.dispose();
			}
		});

		it('DEFERRED (the fix): getCommits() resolves immediately; git status runs in the background afterwards', async () => {
			const source = new DataSource({ path: 'git', version: '2.30.0' }, onDidChangeConfiguration.subscribe, onDidChangeGitExecutable.subscribe, logger);
			try {
				const repoInfo = await source.getRepoInfo(repo, true, false, []);
				const deferred = await timed(() => source.getCommits(
					repo, null, null, INITIAL_LOAD_COMMITS, true, true, false, false,
					CommitOrdering.Date, repoInfo.remotes, [], repoInfo.stashes, null, false, null, true
				));
				record('7. DEFERRED first paint (graph renders immediately)', deferred.ms);
				expect(deferred.value.error).toBeNull();

				const followUp = await timed(() => source.getUncommittedChanges(repo));
				record('8. background git status (used to gate the response, now runs AFTER the paint)', followUp.ms);

				const speedup = blockingMs / Math.max(1, deferred.ms);
				record('=> first-paint speed-up on a large untracked tree (blocking -> deferred)', 0);
				// eslint-disable-next-line no-console
				console.log('\n  [blocking: ' + blockingMs + ' ms, deferred: ' + deferred.ms + ' ms, background status: ' + followUp.ms + ' ms, ' + speedup.toFixed(1) + 'x faster to first paint]');
			} finally {
				source.dispose();
			}
		});
	});
});
