/**
 * Smoke test: run the compiled web bundle (media/out.min.js) in a jsdom
 * environment with a realistic initialState, to catch runtime errors that
 * would leave the Git Graph View blank in VS Code.
 */
/**
 * @jest-environment jsdom
 */
import * as fs from 'fs';
import * as path from 'path';

declare const document: any;
declare const window: any;
declare const Event: any;

describe('Webview smoke test (media/out.min.js)', () => {
	let windowErrors: string[];

	beforeEach(() => {
		windowErrors = [];
	});

	test('loads and constructs the view without throwing', () => {
		const repo = '/path/to/repo';
		const initialState = {
			config: {
				commitOrdering: 'date',
				commitDetailsView: { autoCenter: true, fileTreeCompactFolders: true, fileViewType: 'File Tree', location: 'Inline' },
				contextMenuActionsVisibility: {},
				customBranchGlobPatterns: [],
				customEmojiShortcodeMappings: [],
				customPullRequestProviders: [],
				defaultColumnVisibility: { date: true, author: true, commit: true, signature: false },
				dialogDefaults: {},
				enhancedAccessibility: false,
				fetchAndPrune: false,
				fetchAndPruneTags: false,
				fetchAvatars: false,
				gerrit: {
					enabled: true, remote: 'origin', fetchMode: 'latest', fetchLimit: 10, patchsets: 'latest',
					autoFetch: false, showChangeRefs: true, includeChangeCommits: true, showReviewProgress: true,
					showMetaCommits: 'collapsed', statusFilter: { new: true, merged: false, abandoned: false, wip: false },
					showPushButton: true, showControlsBar: true
				},
				graph: { colours: ['#0085d9'], style: 'rounded', issueLinking: {}, grid: { x: 10, y: 24, offsetX: 8, offsetY: 8, expandY: 8 } },
				initialLoadCommits: 500,
				keybindings: {},
				loadMoreCommits: 100,
				loadMoreCommitsAutomatically: true,
				muteCommits: [],
				referenceLabels: { branchLabelsAlignedToGraph: false, tagLabelsOnRight: false },
				showCommitBodyInline: false,
				stickyHeader: true,
				tabIconColourTheme: 'colour'
			},
			loadViewTo: null,
			repos: { [repo]: 'repo' }
		};
		const globalState = { avatars: {} };
		const workspaceState = {};

		(globalThis as any).onerror = (msg: any) => { windowErrors.push(String(msg)); };
		(globalThis as any).acquireVsCodeApi = () => ({ postMessage: () => undefined, getState: () => undefined, setState: () => undefined });

		// DOM mirroring the controls markup generated by GitGraphView (including the Gerrit controls row)
		document.body.innerHTML = '<div id="view" tabindex="-1">' +
			'<div id="controls">' +
			'<span id="repoControl"><div id="repoDropdown" class="dropdown"></div></span>' +
			'<span id="branchControl"><div id="branchDropdown" class="dropdown"></div></span>' +
			'<span id="authorControl"><div id="authorDropdown" class="dropdown"></div></span>' +
			'<label id="showRemoteBranchesControl"><input type="checkbox" id="showRemoteBranchesCheckbox" tabindex="-1"></label>' +
			'<div id="currentBtn"></div><div id="findBtn"></div><div id="filterBtn"></div><div id="terminalBtn"></div><div id="settingsBtn"></div><div id="fetchBtn"></div><div id="refreshBtn"></div>' +
			'</div>' +
			'<div id="gerritControls">' +
			'<span class="gerritRowLabel">Gerrit:</span>' +
			'<span id="gerritFilterControl"></span>' +
			'<div id="gerritAmendBtn"></div>' +
			'<div id="gerritSubmitBtn"></div>' +
			'<div id="gerritClearRefsBtn"></div>' +
			'</div>' +
			'<div id="content"><div id="commitGraph"></div><div id="commitTable"></div></div>' +
			'<div id="footer"></div>' +
			'</div>';

		// Minimal DOM expected by the bundle (#view load is deferred until the repo is loaded)
		const script = fs.readFileSync(path.join(__dirname, '..', 'media', 'out.min.js'), 'utf8');
		expect(() => {
			// eslint-disable-next-line no-eval
			eval('var initialState = ' + JSON.stringify(initialState) + ', globalState = ' + JSON.stringify(globalState) + ', workspaceState = ' + JSON.stringify(workspaceState) + ';\n' + script);
		}).not.toThrow();

		expect(windowErrors).toEqual([]);

		// The bundle defers construction until the window 'load' event; trigger it manually (it fired before the eval).
		// jsdom doesn't implement Element.scroll, which the view constructor uses.
		(window as any).Element.prototype.scroll = () => undefined;
		window.dispatchEvent(new Event('load'));

		// The Gerrit controls row should be initialised: 4 status chips and labelled amend/submit/clear buttons
		expect(document.getElementById('gerritFilterControl')!.querySelectorAll('.gerritFilterChip').length).toBe(4);
		expect(document.getElementById('gerritAmendBtn')!.textContent).toContain('Amend');
		expect(document.getElementById('gerritSubmitBtn')!.textContent).toContain('Submit');
		expect(document.getElementById('gerritClearRefsBtn')!.textContent).toContain('Clear');

		// The path filter button should be initialised with the filter icon and an inactive state
		expect(document.getElementById('filterBtn')!.innerHTML).toContain('<svg');
		expect(document.getElementById('filterBtn')!.title).toContain('Filter Commits by Path');
		expect(document.getElementById('filterBtn')!.className).not.toContain('active');
	});
});
